AllCops:
  Exclude:
    - 'bin/**/*'

Layout/EndOfLine:
  EnforcedStyle: lf

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Documentation:
  Enabled: false
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'config/**/*'
    - 'test/**/*'
