AllCops:
  Exclude:
    - 'bin/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/**/*'
    - 'test/**/*'
