version: '2'
services:
  bundle:
    image: busybox
    volumes:
      - /bundle
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
  app:
    build: .
    stdin_open: true
    tty: true
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    volumes_from:
      - bundle
