sqlite3: &sqlite3
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000

postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  min_messages: ERROR
  reconnect: false

development:
  <<: *sqlite3

test: &test
  <<: *sqlite3

production:
  <<: *postgresql
